project:
  type: website

website:
  title: "IFP: Suspects & Deception"
  
  sidebar:
    background: red
    logo: "images/LMLLOGO.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: "https://github.com/DrDeception/23-24_IFP"
        text: GitHub
      # - icon: cloud-fill
      #   href: 
      #   text: RStudio Cloud
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
csl: apa7.csl 
format:
  html:
    theme: cosmo
    mainfont: "Atkinson Hyperlegible"
   # css: styles.css
    toc: true
    

execute: 
  freeze: auto

